-- OLTPSemi_55.OLTP55_Schema.[Container] -> fdp.oltp55_schema_container
-- Generated from the table DDL; see mssql/tools/introspect_container.py.

CREATE DATABASE IF NOT EXISTS fdp;

CREATE TABLE IF NOT EXISTS fdp.oltp55_schema_container
(
    AlternateName1 String,
    AlternateName2 String,
    BatchComments String,
    BatchId String,
    BatchIdSequence Int32,
    BatchNo String,
    BatchStatus Int32,
    BillOfProcessId String,
    BinSize String,
    BOMId String,
    CDOTypeId Int32,
    ChangeCount Int32,
    ChildCount Int32,
    ConsumingOrder String,
    ContainerComments String,
    ContainerId String,
    ContainerName String,
    ContainerStartGUID String,
    ContainerTxnSequence Int32,
    CurrentHoldCount Int32,
    CurrentReworkCount Int32,
    CurrentStatusId String,
    CurrentThruputChildCount Int32,
    CurrentThruputQty Float64,
    CurrentThruputQty2 Float64,
    CurrentThruputUnitCount Int32,
    CurrentWIPLotId String,
    CustomerId String,
    DateCode String,
    Description String,
    DetailId String,
    Direction Int32,
    DocumentSetId String,
    DueDate Nullable(DateTime64(3)),
    DueDateGMT Nullable(DateTime64(3)),
    EquipmentCount Int32,
    EquipmentLoadingCount Int32,
    ExpirationDate Nullable(DateTime64(3)),
    ExpirationDateGMT Nullable(DateTime64(3)),
    FactoryStartDate Nullable(DateTime64(3)),
    FactoryStartDateGMT Nullable(DateTime64(3)),
    FactoryStartQty Float64,
    FactoryStartQty2 Float64,
    FactoryStartUOM2Id String,
    FactoryStartUOMId String,
    FirstName String,
    FutureCombineCount Int32,
    FutureCombineParentLotId String,
    FutureCombineSpecId String,
    FutureHoldCount Int32,
    HoldLocationDuration Float64,
    HoldLocationId String,
    HoldLocationStartTimestamp Nullable(DateTime64(3)),
    HoldLocationTotalDuration Float64,
    HoldReasonId String,
    InQualityControl Int32,
    InsertionNumber Int32,
    IsEShip Bool,
    IsSSUseStep Bool,
    IssuedToContainerId String,
    ItemsCount Int32,
    LastActivityDate Nullable(DateTime64(3)),
    LastActivityDateGMT Nullable(DateTime64(3)),
    LastCarrierId String,
    LastCompletionDate Nullable(DateTime64(3)),
    LastCompletionDateGMT Nullable(DateTime64(3)),
    LastIntegrationTxnId String,
    LastInventoryStepId String,
    LastLotCarriersSetupHistoryId String,
    LastLotSortingId String,
    LastLotSortIQCId String,
    LastLotSortSQAId String,
    LastLotTestedTestParamsBinId String,
    LastLotTestedTestParamsId String,
    LastMoveOutTimestamp Nullable(DateTime64(3)),
    LastMoveOutUsername String,
    LastRevTxnId String,
    LastScheduleDataId String,
    LastStepId String,
    LeadFree Int32,
    LevelId String,
    LoanCount Int32,
    LoanSequence Int32,
    LotAttributesId String,
    LotDispositionId String,
    MasterRecipeId String,
    MaxTimeWindowCount Int32,
    MaxTimeWindowStopped Bool,
    MfgOrderId String,
    MfgPartNumber String,
    MoveInQty Float64,
    MoveInQty2 Float64,
    MoveInTimestamp Nullable(DateTime64(3)),
    MoveInUsername String,
    NickName String,
    ObjectType String,
    OnHoldDate Nullable(DateTime64(3)),
    OriginalContainerId String,
    OriginalFactoryId String,
    OriginalQty Float64,
    OriginalQty2 Float64,
    OriginalStartDate Nullable(DateTime64(3)),
    OriginalStartDateGMT Nullable(DateTime64(3)),
    OriginalUOM2Id String,
    OriginalUOMId String,
    OwnerId String,
    ParentContainerId String,
    PlannedProductId String,
    PlannedQty Float64,
    PlannedQty2 Float64,
    PlannedQtyUOM2Id String,
    PlannedQtyUOMId String,
    PlannedStartDate Nullable(DateTime64(3)),
    PlannedStartDateGMT Nullable(DateTime64(3)),
    PriorityCodeId String,
    ProcessSpecId String,
    ProductId String,
    Qty Float64,
    Qty2 Float64,
    QtyScheduled Float64,
    QualityStatusReasonId String,
    ReceivingTimeStamp Nullable(DateTime64(3)),
    RelativePriority Int32,
    RequestDate Nullable(DateTime64(3)),
    RequestDateGMT Nullable(DateTime64(3)),
    ReworkHoldTriggered Bool,
    SalesOrderId String,
    SamplingLotId String,
    SamplingPassed Bool,
    SamplingRequired Bool,
    ScheduleCount Int32,
    ScheduleDataId String,
    ScheduleResidueQty Float64,
    scsCarrierContainerId String,
    scsCurrentContainerStepSequenc Int32,
    scsIsCarrierContainer Bool,
    scsIsMultiLevelStart Bool,
    scsLastMoveOutTimestampGMT Nullable(DateTime64(3)),
    scsLotCarrierPositionId String,
    scsMoveInTimestampGMT Nullable(DateTime64(3)),
    scsOnHoldDateGMT Nullable(DateTime64(3)),
    scsPreactorLastSequence Int32,
    scsPrevContainerStepSequence Int32,
    ShapeName String,
    SkipDispatchPlan Bool,
    SPCChartSaveOptionsEnumId String,
    SpecStatusId String,
    SplitCount Int32,
    SplitFromId String,
    ss_FeederId String,
    ss_MfgLineId String,
    ss_SendAheadDetailsId String,
    ss_ToBeHeldAtMoveOut Bool,
    SSExists Bool,
    SSId String,
    SSMoveBackFromSpecId String,
    SSMoveBackFromStepId String,
    SSMoveBackToSpecId String,
    SSMoveBackToStepId String,
    SSMoveOutFromSpecId String,
    SSMoveOutFromStepId String,
    SSMoveOutToSpecId String,
    SSMoveOutToStepId String,
    StartParentContainerId String,
    StartReasonId String,
    Status Int32,
    StepLogicCriteriaId String,
    Supplier String,
    SupplyFromName String,
    SupplyFromType String,
    TestIQCCount Int32,
    ThisContainerLost Bool,
    ThruputAdjustmentChildCount Int32,
    ThruputAdjustmentQty Float64,
    ThruputAdjustmentQty2 Float64,
    ThruputAdjustmentUnitCount Int32,
    TxnTimestamp Nullable(DateTime64(3)),
    UnitCount Int32,
    UOM2Id String,
    UOMId String,
    VarianceApprovedBy String,
    VarianceComments String,
    VarianceQty Float64,
    VarianceReasonId String,
    VendorItemId String,
    WIPMsgDefMgrId String,
    HoldId String,
    bpCalculateQtyRequired Bool,
    isAssociatedCarrierId String,
    isAutoStart Bool,
    isCarrier Bool,
    isCarrierSlot Int32,
    isFailed Bool,
    isHoldReasonName String,
    isInventoryLocationId String,
    isMaterialManageEnabled Bool,
    isProductName String,
    isProductRevision String,
    isRepairedDefectCount Int32,
    wdc_MaterialLocationId String,
    ProductionComplete Bool
)
ENGINE = ReplacingMergeTree
ORDER BY ContainerId;

CREATE TABLE IF NOT EXISTS fdp.oltp55_schema_container_kafka
(
    msg String
) ENGINE = Kafka
SETTINGS
    kafka_broker_list = 'kafka:19092',
    kafka_topic_list = 'oltp55_schema_container',
    kafka_group_name = 'fdp-oltp55_schema_container',
    kafka_format = 'JSONAsString',
    kafka_num_consumers = 1,
    kafka_flush_interval_ms = 1000,
    kafka_max_block_size = 1048576,
    kafka_skip_broken_messages = 1;

CREATE MATERIALIZED VIEW IF NOT EXISTS fdp.mv_oltp55_schema_container
TO fdp.oltp55_schema_container
AS
SELECT
    JSONExtractString(msg, 'after', 'AlternateName1') AS AlternateName1,
    JSONExtractString(msg, 'after', 'AlternateName2') AS AlternateName2,
    JSONExtractString(msg, 'after', 'BatchComments') AS BatchComments,
    JSONExtractString(msg, 'after', 'BatchId') AS BatchId,
    CAST(JSONExtractInt(msg, 'after', 'BatchIdSequence') AS Int32) AS BatchIdSequence,
    JSONExtractString(msg, 'after', 'BatchNo') AS BatchNo,
    CAST(JSONExtractInt(msg, 'after', 'BatchStatus') AS Int32) AS BatchStatus,
    JSONExtractString(msg, 'after', 'BillOfProcessId') AS BillOfProcessId,
    JSONExtractString(msg, 'after', 'BinSize') AS BinSize,
    JSONExtractString(msg, 'after', 'BOMId') AS BOMId,
    CAST(JSONExtractInt(msg, 'after', 'CDOTypeId') AS Int32) AS CDOTypeId,
    CAST(JSONExtractInt(msg, 'after', 'ChangeCount') AS Int32) AS ChangeCount,
    CAST(JSONExtractInt(msg, 'after', 'ChildCount') AS Int32) AS ChildCount,
    JSONExtractString(msg, 'after', 'ConsumingOrder') AS ConsumingOrder,
    JSONExtractString(msg, 'after', 'ContainerComments') AS ContainerComments,
    JSONExtractString(msg, 'after', 'ContainerId') AS ContainerId,
    JSONExtractString(msg, 'after', 'ContainerName') AS ContainerName,
    JSONExtractString(msg, 'after', 'ContainerStartGUID') AS ContainerStartGUID,
    CAST(JSONExtractInt(msg, 'after', 'ContainerTxnSequence') AS Int32) AS ContainerTxnSequence,
    CAST(JSONExtractInt(msg, 'after', 'CurrentHoldCount') AS Int32) AS CurrentHoldCount,
    CAST(JSONExtractInt(msg, 'after', 'CurrentReworkCount') AS Int32) AS CurrentReworkCount,
    JSONExtractString(msg, 'after', 'CurrentStatusId') AS CurrentStatusId,
    CAST(JSONExtractInt(msg, 'after', 'CurrentThruputChildCount') AS Int32) AS CurrentThruputChildCount,
    JSONExtractFloat(msg, 'after', 'CurrentThruputQty') AS CurrentThruputQty,
    JSONExtractFloat(msg, 'after', 'CurrentThruputQty2') AS CurrentThruputQty2,
    CAST(JSONExtractInt(msg, 'after', 'CurrentThruputUnitCount') AS Int32) AS CurrentThruputUnitCount,
    JSONExtractString(msg, 'after', 'CurrentWIPLotId') AS CurrentWIPLotId,
    JSONExtractString(msg, 'after', 'CustomerId') AS CustomerId,
    JSONExtractString(msg, 'after', 'DateCode') AS DateCode,
    JSONExtractString(msg, 'after', 'Description') AS Description,
    JSONExtractString(msg, 'after', 'DetailId') AS DetailId,
    CAST(JSONExtractInt(msg, 'after', 'Direction') AS Int32) AS Direction,
    JSONExtractString(msg, 'after', 'DocumentSetId') AS DocumentSetId,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'DueDate'), 3) AS DueDate,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'DueDateGMT'), 3) AS DueDateGMT,
    CAST(JSONExtractInt(msg, 'after', 'EquipmentCount') AS Int32) AS EquipmentCount,
    CAST(JSONExtractInt(msg, 'after', 'EquipmentLoadingCount') AS Int32) AS EquipmentLoadingCount,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'ExpirationDate'), 3) AS ExpirationDate,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'ExpirationDateGMT'), 3) AS ExpirationDateGMT,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'FactoryStartDate'), 3) AS FactoryStartDate,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'FactoryStartDateGMT'), 3) AS FactoryStartDateGMT,
    JSONExtractFloat(msg, 'after', 'FactoryStartQty') AS FactoryStartQty,
    JSONExtractFloat(msg, 'after', 'FactoryStartQty2') AS FactoryStartQty2,
    JSONExtractString(msg, 'after', 'FactoryStartUOM2Id') AS FactoryStartUOM2Id,
    JSONExtractString(msg, 'after', 'FactoryStartUOMId') AS FactoryStartUOMId,
    JSONExtractString(msg, 'after', 'FirstName') AS FirstName,
    CAST(JSONExtractInt(msg, 'after', 'FutureCombineCount') AS Int32) AS FutureCombineCount,
    JSONExtractString(msg, 'after', 'FutureCombineParentLotId') AS FutureCombineParentLotId,
    JSONExtractString(msg, 'after', 'FutureCombineSpecId') AS FutureCombineSpecId,
    CAST(JSONExtractInt(msg, 'after', 'FutureHoldCount') AS Int32) AS FutureHoldCount,
    JSONExtractFloat(msg, 'after', 'HoldLocationDuration') AS HoldLocationDuration,
    JSONExtractString(msg, 'after', 'HoldLocationId') AS HoldLocationId,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'HoldLocationStartTimestamp'), 3) AS HoldLocationStartTimestamp,
    JSONExtractFloat(msg, 'after', 'HoldLocationTotalDuration') AS HoldLocationTotalDuration,
    JSONExtractString(msg, 'after', 'HoldReasonId') AS HoldReasonId,
    CAST(JSONExtractInt(msg, 'after', 'InQualityControl') AS Int32) AS InQualityControl,
    CAST(JSONExtractInt(msg, 'after', 'InsertionNumber') AS Int32) AS InsertionNumber,
    JSONExtractBool(msg, 'after', 'IsEShip') AS IsEShip,
    JSONExtractBool(msg, 'after', 'IsSSUseStep') AS IsSSUseStep,
    JSONExtractString(msg, 'after', 'IssuedToContainerId') AS IssuedToContainerId,
    CAST(JSONExtractInt(msg, 'after', 'ItemsCount') AS Int32) AS ItemsCount,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'LastActivityDate'), 3) AS LastActivityDate,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'LastActivityDateGMT'), 3) AS LastActivityDateGMT,
    JSONExtractString(msg, 'after', 'LastCarrierId') AS LastCarrierId,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'LastCompletionDate'), 3) AS LastCompletionDate,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'LastCompletionDateGMT'), 3) AS LastCompletionDateGMT,
    JSONExtractString(msg, 'after', 'LastIntegrationTxnId') AS LastIntegrationTxnId,
    JSONExtractString(msg, 'after', 'LastInventoryStepId') AS LastInventoryStepId,
    JSONExtractString(msg, 'after', 'LastLotCarriersSetupHistoryId') AS LastLotCarriersSetupHistoryId,
    JSONExtractString(msg, 'after', 'LastLotSortingId') AS LastLotSortingId,
    JSONExtractString(msg, 'after', 'LastLotSortIQCId') AS LastLotSortIQCId,
    JSONExtractString(msg, 'after', 'LastLotSortSQAId') AS LastLotSortSQAId,
    JSONExtractString(msg, 'after', 'LastLotTestedTestParamsBinId') AS LastLotTestedTestParamsBinId,
    JSONExtractString(msg, 'after', 'LastLotTestedTestParamsId') AS LastLotTestedTestParamsId,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'LastMoveOutTimestamp'), 3) AS LastMoveOutTimestamp,
    JSONExtractString(msg, 'after', 'LastMoveOutUsername') AS LastMoveOutUsername,
    JSONExtractString(msg, 'after', 'LastRevTxnId') AS LastRevTxnId,
    JSONExtractString(msg, 'after', 'LastScheduleDataId') AS LastScheduleDataId,
    JSONExtractString(msg, 'after', 'LastStepId') AS LastStepId,
    CAST(JSONExtractInt(msg, 'after', 'LeadFree') AS Int32) AS LeadFree,
    JSONExtractString(msg, 'after', 'LevelId') AS LevelId,
    CAST(JSONExtractInt(msg, 'after', 'LoanCount') AS Int32) AS LoanCount,
    CAST(JSONExtractInt(msg, 'after', 'LoanSequence') AS Int32) AS LoanSequence,
    JSONExtractString(msg, 'after', 'LotAttributesId') AS LotAttributesId,
    JSONExtractString(msg, 'after', 'LotDispositionId') AS LotDispositionId,
    JSONExtractString(msg, 'after', 'MasterRecipeId') AS MasterRecipeId,
    CAST(JSONExtractInt(msg, 'after', 'MaxTimeWindowCount') AS Int32) AS MaxTimeWindowCount,
    JSONExtractBool(msg, 'after', 'MaxTimeWindowStopped') AS MaxTimeWindowStopped,
    JSONExtractString(msg, 'after', 'MfgOrderId') AS MfgOrderId,
    JSONExtractString(msg, 'after', 'MfgPartNumber') AS MfgPartNumber,
    JSONExtractFloat(msg, 'after', 'MoveInQty') AS MoveInQty,
    JSONExtractFloat(msg, 'after', 'MoveInQty2') AS MoveInQty2,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'MoveInTimestamp'), 3) AS MoveInTimestamp,
    JSONExtractString(msg, 'after', 'MoveInUsername') AS MoveInUsername,
    JSONExtractString(msg, 'after', 'NickName') AS NickName,
    JSONExtractString(msg, 'after', 'ObjectType') AS ObjectType,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'OnHoldDate'), 3) AS OnHoldDate,
    JSONExtractString(msg, 'after', 'OriginalContainerId') AS OriginalContainerId,
    JSONExtractString(msg, 'after', 'OriginalFactoryId') AS OriginalFactoryId,
    JSONExtractFloat(msg, 'after', 'OriginalQty') AS OriginalQty,
    JSONExtractFloat(msg, 'after', 'OriginalQty2') AS OriginalQty2,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'OriginalStartDate'), 3) AS OriginalStartDate,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'OriginalStartDateGMT'), 3) AS OriginalStartDateGMT,
    JSONExtractString(msg, 'after', 'OriginalUOM2Id') AS OriginalUOM2Id,
    JSONExtractString(msg, 'after', 'OriginalUOMId') AS OriginalUOMId,
    JSONExtractString(msg, 'after', 'OwnerId') AS OwnerId,
    JSONExtractString(msg, 'after', 'ParentContainerId') AS ParentContainerId,
    JSONExtractString(msg, 'after', 'PlannedProductId') AS PlannedProductId,
    JSONExtractFloat(msg, 'after', 'PlannedQty') AS PlannedQty,
    JSONExtractFloat(msg, 'after', 'PlannedQty2') AS PlannedQty2,
    JSONExtractString(msg, 'after', 'PlannedQtyUOM2Id') AS PlannedQtyUOM2Id,
    JSONExtractString(msg, 'after', 'PlannedQtyUOMId') AS PlannedQtyUOMId,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'PlannedStartDate'), 3) AS PlannedStartDate,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'PlannedStartDateGMT'), 3) AS PlannedStartDateGMT,
    JSONExtractString(msg, 'after', 'PriorityCodeId') AS PriorityCodeId,
    JSONExtractString(msg, 'after', 'ProcessSpecId') AS ProcessSpecId,
    JSONExtractString(msg, 'after', 'ProductId') AS ProductId,
    JSONExtractFloat(msg, 'after', 'Qty') AS Qty,
    JSONExtractFloat(msg, 'after', 'Qty2') AS Qty2,
    JSONExtractFloat(msg, 'after', 'QtyScheduled') AS QtyScheduled,
    JSONExtractString(msg, 'after', 'QualityStatusReasonId') AS QualityStatusReasonId,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'ReceivingTimeStamp'), 3) AS ReceivingTimeStamp,
    CAST(JSONExtractInt(msg, 'after', 'RelativePriority') AS Int32) AS RelativePriority,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'RequestDate'), 3) AS RequestDate,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'RequestDateGMT'), 3) AS RequestDateGMT,
    JSONExtractBool(msg, 'after', 'ReworkHoldTriggered') AS ReworkHoldTriggered,
    JSONExtractString(msg, 'after', 'SalesOrderId') AS SalesOrderId,
    JSONExtractString(msg, 'after', 'SamplingLotId') AS SamplingLotId,
    JSONExtractBool(msg, 'after', 'SamplingPassed') AS SamplingPassed,
    JSONExtractBool(msg, 'after', 'SamplingRequired') AS SamplingRequired,
    CAST(JSONExtractInt(msg, 'after', 'ScheduleCount') AS Int32) AS ScheduleCount,
    JSONExtractString(msg, 'after', 'ScheduleDataId') AS ScheduleDataId,
    JSONExtractFloat(msg, 'after', 'ScheduleResidueQty') AS ScheduleResidueQty,
    JSONExtractString(msg, 'after', 'scsCarrierContainerId') AS scsCarrierContainerId,
    CAST(JSONExtractInt(msg, 'after', 'scsCurrentContainerStepSequenc') AS Int32) AS scsCurrentContainerStepSequenc,
    JSONExtractBool(msg, 'after', 'scsIsCarrierContainer') AS scsIsCarrierContainer,
    JSONExtractBool(msg, 'after', 'scsIsMultiLevelStart') AS scsIsMultiLevelStart,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'scsLastMoveOutTimestampGMT'), 3) AS scsLastMoveOutTimestampGMT,
    JSONExtractString(msg, 'after', 'scsLotCarrierPositionId') AS scsLotCarrierPositionId,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'scsMoveInTimestampGMT'), 3) AS scsMoveInTimestampGMT,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'scsOnHoldDateGMT'), 3) AS scsOnHoldDateGMT,
    CAST(JSONExtractInt(msg, 'after', 'scsPreactorLastSequence') AS Int32) AS scsPreactorLastSequence,
    CAST(JSONExtractInt(msg, 'after', 'scsPrevContainerStepSequence') AS Int32) AS scsPrevContainerStepSequence,
    JSONExtractString(msg, 'after', 'ShapeName') AS ShapeName,
    JSONExtractBool(msg, 'after', 'SkipDispatchPlan') AS SkipDispatchPlan,
    JSONExtractString(msg, 'after', 'SPCChartSaveOptionsEnumId') AS SPCChartSaveOptionsEnumId,
    JSONExtractString(msg, 'after', 'SpecStatusId') AS SpecStatusId,
    CAST(JSONExtractInt(msg, 'after', 'SplitCount') AS Int32) AS SplitCount,
    JSONExtractString(msg, 'after', 'SplitFromId') AS SplitFromId,
    JSONExtractString(msg, 'after', 'ss_FeederId') AS ss_FeederId,
    JSONExtractString(msg, 'after', 'ss_MfgLineId') AS ss_MfgLineId,
    JSONExtractString(msg, 'after', 'ss_SendAheadDetailsId') AS ss_SendAheadDetailsId,
    JSONExtractBool(msg, 'after', 'ss_ToBeHeldAtMoveOut') AS ss_ToBeHeldAtMoveOut,
    JSONExtractBool(msg, 'after', 'SSExists') AS SSExists,
    JSONExtractString(msg, 'after', 'SSId') AS SSId,
    JSONExtractString(msg, 'after', 'SSMoveBackFromSpecId') AS SSMoveBackFromSpecId,
    JSONExtractString(msg, 'after', 'SSMoveBackFromStepId') AS SSMoveBackFromStepId,
    JSONExtractString(msg, 'after', 'SSMoveBackToSpecId') AS SSMoveBackToSpecId,
    JSONExtractString(msg, 'after', 'SSMoveBackToStepId') AS SSMoveBackToStepId,
    JSONExtractString(msg, 'after', 'SSMoveOutFromSpecId') AS SSMoveOutFromSpecId,
    JSONExtractString(msg, 'after', 'SSMoveOutFromStepId') AS SSMoveOutFromStepId,
    JSONExtractString(msg, 'after', 'SSMoveOutToSpecId') AS SSMoveOutToSpecId,
    JSONExtractString(msg, 'after', 'SSMoveOutToStepId') AS SSMoveOutToStepId,
    JSONExtractString(msg, 'after', 'StartParentContainerId') AS StartParentContainerId,
    JSONExtractString(msg, 'after', 'StartReasonId') AS StartReasonId,
    CAST(JSONExtractInt(msg, 'after', 'Status') AS Int32) AS Status,
    JSONExtractString(msg, 'after', 'StepLogicCriteriaId') AS StepLogicCriteriaId,
    JSONExtractString(msg, 'after', 'Supplier') AS Supplier,
    JSONExtractString(msg, 'after', 'SupplyFromName') AS SupplyFromName,
    JSONExtractString(msg, 'after', 'SupplyFromType') AS SupplyFromType,
    CAST(JSONExtractInt(msg, 'after', 'TestIQCCount') AS Int32) AS TestIQCCount,
    JSONExtractBool(msg, 'after', 'ThisContainerLost') AS ThisContainerLost,
    CAST(JSONExtractInt(msg, 'after', 'ThruputAdjustmentChildCount') AS Int32) AS ThruputAdjustmentChildCount,
    JSONExtractFloat(msg, 'after', 'ThruputAdjustmentQty') AS ThruputAdjustmentQty,
    JSONExtractFloat(msg, 'after', 'ThruputAdjustmentQty2') AS ThruputAdjustmentQty2,
    CAST(JSONExtractInt(msg, 'after', 'ThruputAdjustmentUnitCount') AS Int32) AS ThruputAdjustmentUnitCount,
    parseDateTime64BestEffortOrNull(JSONExtractString(msg, 'after', 'TxnTimestamp'), 3) AS TxnTimestamp,
    CAST(JSONExtractInt(msg, 'after', 'UnitCount') AS Int32) AS UnitCount,
    JSONExtractString(msg, 'after', 'UOM2Id') AS UOM2Id,
    JSONExtractString(msg, 'after', 'UOMId') AS UOMId,
    JSONExtractString(msg, 'after', 'VarianceApprovedBy') AS VarianceApprovedBy,
    JSONExtractString(msg, 'after', 'VarianceComments') AS VarianceComments,
    JSONExtractFloat(msg, 'after', 'VarianceQty') AS VarianceQty,
    JSONExtractString(msg, 'after', 'VarianceReasonId') AS VarianceReasonId,
    JSONExtractString(msg, 'after', 'VendorItemId') AS VendorItemId,
    JSONExtractString(msg, 'after', 'WIPMsgDefMgrId') AS WIPMsgDefMgrId,
    JSONExtractString(msg, 'after', 'HoldId') AS HoldId,
    JSONExtractBool(msg, 'after', 'bpCalculateQtyRequired') AS bpCalculateQtyRequired,
    JSONExtractString(msg, 'after', 'isAssociatedCarrierId') AS isAssociatedCarrierId,
    JSONExtractBool(msg, 'after', 'isAutoStart') AS isAutoStart,
    JSONExtractBool(msg, 'after', 'isCarrier') AS isCarrier,
    CAST(JSONExtractInt(msg, 'after', 'isCarrierSlot') AS Int32) AS isCarrierSlot,
    JSONExtractBool(msg, 'after', 'isFailed') AS isFailed,
    JSONExtractString(msg, 'after', 'isHoldReasonName') AS isHoldReasonName,
    JSONExtractString(msg, 'after', 'isInventoryLocationId') AS isInventoryLocationId,
    JSONExtractBool(msg, 'after', 'isMaterialManageEnabled') AS isMaterialManageEnabled,
    JSONExtractString(msg, 'after', 'isProductName') AS isProductName,
    JSONExtractString(msg, 'after', 'isProductRevision') AS isProductRevision,
    CAST(JSONExtractInt(msg, 'after', 'isRepairedDefectCount') AS Int32) AS isRepairedDefectCount,
    JSONExtractString(msg, 'after', 'wdc_MaterialLocationId') AS wdc_MaterialLocationId,
    JSONExtractBool(msg, 'after', 'ProductionComplete') AS ProductionComplete
FROM fdp.oltp55_schema_container_kafka
WHERE JSONExtractString(msg, 'op') IN ('c', 'u', 'r');
